GPU available?:      True
Network using cuda?: True
epoch 100 completed
epoch 200 completed
epoch 300 completed
epoch 400 completed
epoch 500 completed
Traceback (most recent call last):
  File "wanb.py", line 230, in <module>
    main()
  File "wanb.py", line 228, in main
    wandb.save('src\saved_models\model.h5')
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 882, in save
    os.symlink(abs_path, wandb_path)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\deepu\\Desktop\\MyFolders\\Projects\\PetProjects\\ActivityRecognition\\src\\saved_models\\model.h5' -> 'C:\\Users\\deepu\\Desktop\\MyFolders\\Projects\\PetProjects\\ActivityRecognition\\wandb\\run-20201224_174504-xavanc8q\\files\\src\\saved_models\\model.h5'
